sudo: required
language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - build-essential
dist: bionic
before_install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install yasm; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install yasm; fi
  - rustup component add rustfmt

script: |
    travis_wait cargo build --verbose --features "build"
    cargo test  --verbose --features "build"

after_failure:
  - find /usr -type f 2>/dev/null | grep -E 'lib(avcodec/version|avcodec/avcodec).h$' | xargs -I THEFILE -- sh -c 'echo "=== THEFILE ==="; cat THEFILE'
